# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

scoreboard players tag @s remove b7s:home_x_25
scoreboard players tag @s remove b7s:home_x_24
scoreboard players tag @s remove b7s:home_x_23
scoreboard players tag @s remove b7s:home_x_22
scoreboard players tag @s remove b7s:home_x_21
scoreboard players tag @s remove b7s:home_x_20
scoreboard players tag @s remove b7s:home_x_19
scoreboard players tag @s remove b7s:home_x_18
scoreboard players tag @s remove b7s:home_x_17
scoreboard players tag @s remove b7s:home_x_16
scoreboard players tag @s remove b7s:home_x_15
scoreboard players tag @s remove b7s:home_x_14
scoreboard players tag @s remove b7s:home_x_13
scoreboard players tag @s remove b7s:home_x_12
scoreboard players tag @s remove b7s:home_x_11
scoreboard players tag @s remove b7s:home_x_10
scoreboard players tag @s remove b7s:home_x_9
scoreboard players tag @s remove b7s:home_x_8
scoreboard players tag @s remove b7s:home_x_7
scoreboard players tag @s remove b7s:home_x_6
scoreboard players tag @s remove b7s:home_x_5
scoreboard players tag @s remove b7s:home_x_4
scoreboard players tag @s remove b7s:home_x_3
scoreboard players tag @s remove b7s:home_x_2
scoreboard players tag @s remove b7s:home_x_1
scoreboard players tag @s remove b7s:home_x_0

scoreboard players tag @s remove b7s:home_y_12
scoreboard players tag @s remove b7s:home_y_11
scoreboard players tag @s remove b7s:home_y_10
scoreboard players tag @s remove b7s:home_y_9
scoreboard players tag @s remove b7s:home_y_8
scoreboard players tag @s remove b7s:home_y_7
scoreboard players tag @s remove b7s:home_y_6
scoreboard players tag @s remove b7s:home_y_5
scoreboard players tag @s remove b7s:home_y_4
scoreboard players tag @s remove b7s:home_y_3
scoreboard players tag @s remove b7s:home_y_2
scoreboard players tag @s remove b7s:home_y_1
scoreboard players tag @s remove b7s:home_y_0

scoreboard players tag @s remove b7s:home_z_25
scoreboard players tag @s remove b7s:home_z_24
scoreboard players tag @s remove b7s:home_z_23
scoreboard players tag @s remove b7s:home_z_22
scoreboard players tag @s remove b7s:home_z_21
scoreboard players tag @s remove b7s:home_z_20
scoreboard players tag @s remove b7s:home_z_19
scoreboard players tag @s remove b7s:home_z_18
scoreboard players tag @s remove b7s:home_z_17
scoreboard players tag @s remove b7s:home_z_16
scoreboard players tag @s remove b7s:home_z_15
scoreboard players tag @s remove b7s:home_z_14
scoreboard players tag @s remove b7s:home_z_13
scoreboard players tag @s remove b7s:home_z_12
scoreboard players tag @s remove b7s:home_z_11
scoreboard players tag @s remove b7s:home_z_10
scoreboard players tag @s remove b7s:home_z_9
scoreboard players tag @s remove b7s:home_z_8
scoreboard players tag @s remove b7s:home_z_7
scoreboard players tag @s remove b7s:home_z_6
scoreboard players tag @s remove b7s:home_z_5
scoreboard players tag @s remove b7s:home_z_4
scoreboard players tag @s remove b7s:home_z_3
scoreboard players tag @s remove b7s:home_z_2
scoreboard players tag @s remove b7s:home_z_1
scoreboard players tag @s remove b7s:home_z_0

scoreboard players tag @s[tag=b7s:x_25] add b7s:home_x_25
scoreboard players tag @s[tag=b7s:x_24] add b7s:home_x_24
scoreboard players tag @s[tag=b7s:x_23] add b7s:home_x_23
scoreboard players tag @s[tag=b7s:x_22] add b7s:home_x_22
scoreboard players tag @s[tag=b7s:x_21] add b7s:home_x_21
scoreboard players tag @s[tag=b7s:x_20] add b7s:home_x_20
scoreboard players tag @s[tag=b7s:x_19] add b7s:home_x_19
scoreboard players tag @s[tag=b7s:x_18] add b7s:home_x_18
scoreboard players tag @s[tag=b7s:x_17] add b7s:home_x_17
scoreboard players tag @s[tag=b7s:x_16] add b7s:home_x_16
scoreboard players tag @s[tag=b7s:x_15] add b7s:home_x_15
scoreboard players tag @s[tag=b7s:x_14] add b7s:home_x_14
scoreboard players tag @s[tag=b7s:x_13] add b7s:home_x_13
scoreboard players tag @s[tag=b7s:x_12] add b7s:home_x_12
scoreboard players tag @s[tag=b7s:x_11] add b7s:home_x_11
scoreboard players tag @s[tag=b7s:x_10] add b7s:home_x_10
scoreboard players tag @s[tag=b7s:x_9] add b7s:home_x_9
scoreboard players tag @s[tag=b7s:x_8] add b7s:home_x_8
scoreboard players tag @s[tag=b7s:x_7] add b7s:home_x_7
scoreboard players tag @s[tag=b7s:x_6] add b7s:home_x_6
scoreboard players tag @s[tag=b7s:x_5] add b7s:home_x_5
scoreboard players tag @s[tag=b7s:x_4] add b7s:home_x_4
scoreboard players tag @s[tag=b7s:x_3] add b7s:home_x_3
scoreboard players tag @s[tag=b7s:x_2] add b7s:home_x_2
scoreboard players tag @s[tag=b7s:x_1] add b7s:home_x_1
scoreboard players tag @s[tag=b7s:x_0] add b7s:home_x_0

scoreboard players tag @s[tag=b7s:y_12] add b7s:home_y_12
scoreboard players tag @s[tag=b7s:y_11] add b7s:home_y_11
scoreboard players tag @s[tag=b7s:y_10] add b7s:home_y_10
scoreboard players tag @s[tag=b7s:y_9] add b7s:home_y_9
scoreboard players tag @s[tag=b7s:y_8] add b7s:home_y_8
scoreboard players tag @s[tag=b7s:y_7] add b7s:home_y_7
scoreboard players tag @s[tag=b7s:y_6] add b7s:home_y_6
scoreboard players tag @s[tag=b7s:y_5] add b7s:home_y_5
scoreboard players tag @s[tag=b7s:y_4] add b7s:home_y_4
scoreboard players tag @s[tag=b7s:y_3] add b7s:home_y_3
scoreboard players tag @s[tag=b7s:y_2] add b7s:home_y_2
scoreboard players tag @s[tag=b7s:y_1] add b7s:home_y_1
scoreboard players tag @s[tag=b7s:y_0] add b7s:home_y_0

scoreboard players tag @s[tag=b7s:z_25] add b7s:home_z_25
scoreboard players tag @s[tag=b7s:z_24] add b7s:home_z_24
scoreboard players tag @s[tag=b7s:z_23] add b7s:home_z_23
scoreboard players tag @s[tag=b7s:z_22] add b7s:home_z_22
scoreboard players tag @s[tag=b7s:z_21] add b7s:home_z_21
scoreboard players tag @s[tag=b7s:z_20] add b7s:home_z_20
scoreboard players tag @s[tag=b7s:z_19] add b7s:home_z_19
scoreboard players tag @s[tag=b7s:z_18] add b7s:home_z_18
scoreboard players tag @s[tag=b7s:z_17] add b7s:home_z_17
scoreboard players tag @s[tag=b7s:z_16] add b7s:home_z_16
scoreboard players tag @s[tag=b7s:z_15] add b7s:home_z_15
scoreboard players tag @s[tag=b7s:z_14] add b7s:home_z_14
scoreboard players tag @s[tag=b7s:z_13] add b7s:home_z_13
scoreboard players tag @s[tag=b7s:z_12] add b7s:home_z_12
scoreboard players tag @s[tag=b7s:z_11] add b7s:home_z_11
scoreboard players tag @s[tag=b7s:z_10] add b7s:home_z_10
scoreboard players tag @s[tag=b7s:z_9] add b7s:home_z_9
scoreboard players tag @s[tag=b7s:z_8] add b7s:home_z_8
scoreboard players tag @s[tag=b7s:z_7] add b7s:home_z_7
scoreboard players tag @s[tag=b7s:z_6] add b7s:home_z_6
scoreboard players tag @s[tag=b7s:z_5] add b7s:home_z_5
scoreboard players tag @s[tag=b7s:z_4] add b7s:home_z_4
scoreboard players tag @s[tag=b7s:z_3] add b7s:home_z_3
scoreboard players tag @s[tag=b7s:z_2] add b7s:home_z_2
scoreboard players tag @s[tag=b7s:z_1] add b7s:home_z_1
scoreboard players tag @s[tag=b7s:z_0] add b7s:home_z_0
