scoreboard players tag @s remove b7s:x_25
scoreboard players tag @s remove b7s:x_24
scoreboard players tag @s remove b7s:x_23
scoreboard players tag @s remove b7s:x_22
scoreboard players tag @s remove b7s:x_21
scoreboard players tag @s remove b7s:x_20
scoreboard players tag @s remove b7s:x_19
scoreboard players tag @s remove b7s:x_18
scoreboard players tag @s remove b7s:x_17
scoreboard players tag @s remove b7s:x_16
scoreboard players tag @s remove b7s:x_15
scoreboard players tag @s remove b7s:x_14
scoreboard players tag @s remove b7s:x_13
scoreboard players tag @s remove b7s:x_12
scoreboard players tag @s remove b7s:x_11
scoreboard players tag @s remove b7s:x_10
scoreboard players tag @s remove b7s:x_9
scoreboard players tag @s remove b7s:x_8
scoreboard players tag @s remove b7s:x_7
scoreboard players tag @s remove b7s:x_6
scoreboard players tag @s remove b7s:x_5
scoreboard players tag @s remove b7s:x_4
scoreboard players tag @s remove b7s:x_3
scoreboard players tag @s remove b7s:x_2
scoreboard players tag @s remove b7s:x_1
scoreboard players tag @s remove b7s:x_0

scoreboard players tag @s remove b7s:y_12
scoreboard players tag @s remove b7s:y_11
scoreboard players tag @s remove b7s:y_10
scoreboard players tag @s remove b7s:y_9
scoreboard players tag @s remove b7s:y_8
scoreboard players tag @s remove b7s:y_7
scoreboard players tag @s remove b7s:y_6
scoreboard players tag @s remove b7s:y_5
scoreboard players tag @s remove b7s:y_4
scoreboard players tag @s remove b7s:y_3
scoreboard players tag @s remove b7s:y_2
scoreboard players tag @s remove b7s:y_1
scoreboard players tag @s remove b7s:y_0

scoreboard players tag @s remove b7s:z_25
scoreboard players tag @s remove b7s:z_24
scoreboard players tag @s remove b7s:z_23
scoreboard players tag @s remove b7s:z_22
scoreboard players tag @s remove b7s:z_21
scoreboard players tag @s remove b7s:z_20
scoreboard players tag @s remove b7s:z_19
scoreboard players tag @s remove b7s:z_18
scoreboard players tag @s remove b7s:z_17
scoreboard players tag @s remove b7s:z_16
scoreboard players tag @s remove b7s:z_15
scoreboard players tag @s remove b7s:z_14
scoreboard players tag @s remove b7s:z_13
scoreboard players tag @s remove b7s:z_12
scoreboard players tag @s remove b7s:z_11
scoreboard players tag @s remove b7s:z_10
scoreboard players tag @s remove b7s:z_9
scoreboard players tag @s remove b7s:z_8
scoreboard players tag @s remove b7s:z_7
scoreboard players tag @s remove b7s:z_6
scoreboard players tag @s remove b7s:z_5
scoreboard players tag @s remove b7s:z_4
scoreboard players tag @s remove b7s:z_3
scoreboard players tag @s remove b7s:z_2
scoreboard players tag @s remove b7s:z_1
scoreboard players tag @s remove b7s:z_0

scoreboard players tag @s[tag=b7s:back_x_25] add b7s:x_25
scoreboard players tag @s[tag=b7s:back_x_24] add b7s:x_24
scoreboard players tag @s[tag=b7s:back_x_23] add b7s:x_23
scoreboard players tag @s[tag=b7s:back_x_22] add b7s:x_22
scoreboard players tag @s[tag=b7s:back_x_21] add b7s:x_21
scoreboard players tag @s[tag=b7s:back_x_20] add b7s:x_20
scoreboard players tag @s[tag=b7s:back_x_19] add b7s:x_19
scoreboard players tag @s[tag=b7s:back_x_18] add b7s:x_18
scoreboard players tag @s[tag=b7s:back_x_17] add b7s:x_17
scoreboard players tag @s[tag=b7s:back_x_16] add b7s:x_16
scoreboard players tag @s[tag=b7s:back_x_15] add b7s:x_15
scoreboard players tag @s[tag=b7s:back_x_14] add b7s:x_14
scoreboard players tag @s[tag=b7s:back_x_13] add b7s:x_13
scoreboard players tag @s[tag=b7s:back_x_12] add b7s:x_12
scoreboard players tag @s[tag=b7s:back_x_11] add b7s:x_11
scoreboard players tag @s[tag=b7s:back_x_10] add b7s:x_10
scoreboard players tag @s[tag=b7s:back_x_9] add b7s:x_9
scoreboard players tag @s[tag=b7s:back_x_8] add b7s:x_8
scoreboard players tag @s[tag=b7s:back_x_7] add b7s:x_7
scoreboard players tag @s[tag=b7s:back_x_6] add b7s:x_6
scoreboard players tag @s[tag=b7s:back_x_5] add b7s:x_5
scoreboard players tag @s[tag=b7s:back_x_4] add b7s:x_4
scoreboard players tag @s[tag=b7s:back_x_3] add b7s:x_3
scoreboard players tag @s[tag=b7s:back_x_2] add b7s:x_2
scoreboard players tag @s[tag=b7s:back_x_1] add b7s:x_1
scoreboard players tag @s[tag=b7s:back_x_0] add b7s:x_0

scoreboard players tag @s[tag=b7s:back_y_12] add b7s:y_12
scoreboard players tag @s[tag=b7s:back_y_11] add b7s:y_11
scoreboard players tag @s[tag=b7s:back_y_10] add b7s:y_10
scoreboard players tag @s[tag=b7s:back_y_9] add b7s:y_9
scoreboard players tag @s[tag=b7s:back_y_8] add b7s:y_8
scoreboard players tag @s[tag=b7s:back_y_7] add b7s:y_7
scoreboard players tag @s[tag=b7s:back_y_6] add b7s:y_6
scoreboard players tag @s[tag=b7s:back_y_5] add b7s:y_5
scoreboard players tag @s[tag=b7s:back_y_4] add b7s:y_4
scoreboard players tag @s[tag=b7s:back_y_3] add b7s:y_3
scoreboard players tag @s[tag=b7s:back_y_2] add b7s:y_2
scoreboard players tag @s[tag=b7s:back_y_1] add b7s:y_1
scoreboard players tag @s[tag=b7s:back_y_0] add b7s:y_0

scoreboard players tag @s[tag=b7s:back_z_25] add b7s:z_25
scoreboard players tag @s[tag=b7s:back_z_24] add b7s:z_24
scoreboard players tag @s[tag=b7s:back_z_23] add b7s:z_23
scoreboard players tag @s[tag=b7s:back_z_22] add b7s:z_22
scoreboard players tag @s[tag=b7s:back_z_21] add b7s:z_21
scoreboard players tag @s[tag=b7s:back_z_20] add b7s:z_20
scoreboard players tag @s[tag=b7s:back_z_19] add b7s:z_19
scoreboard players tag @s[tag=b7s:back_z_18] add b7s:z_18
scoreboard players tag @s[tag=b7s:back_z_17] add b7s:z_17
scoreboard players tag @s[tag=b7s:back_z_16] add b7s:z_16
scoreboard players tag @s[tag=b7s:back_z_15] add b7s:z_15
scoreboard players tag @s[tag=b7s:back_z_14] add b7s:z_14
scoreboard players tag @s[tag=b7s:back_z_13] add b7s:z_13
scoreboard players tag @s[tag=b7s:back_z_12] add b7s:z_12
scoreboard players tag @s[tag=b7s:back_z_11] add b7s:z_11
scoreboard players tag @s[tag=b7s:back_z_10] add b7s:z_10
scoreboard players tag @s[tag=b7s:back_z_9] add b7s:z_9
scoreboard players tag @s[tag=b7s:back_z_8] add b7s:z_8
scoreboard players tag @s[tag=b7s:back_z_7] add b7s:z_7
scoreboard players tag @s[tag=b7s:back_z_6] add b7s:z_6
scoreboard players tag @s[tag=b7s:back_z_5] add b7s:z_5
scoreboard players tag @s[tag=b7s:back_z_4] add b7s:z_4
scoreboard players tag @s[tag=b7s:back_z_3] add b7s:z_3
scoreboard players tag @s[tag=b7s:back_z_2] add b7s:z_2
scoreboard players tag @s[tag=b7s:back_z_1] add b7s:z_1
scoreboard players tag @s[tag=b7s:back_z_0] add b7s:z_0
